### PR TITLE
Update

### PR DESCRIPTION
**Pull request by nik2203**
#31 
PES2UG21CS334
Nikhil Girish

### CODE REVIEW

**Comment by alfadelta10010** [comment]
!bounty 60

**Comment by alfadelta10010** [comment]
@nik2203 looks good, can't merge yet cause need the database itself

**Comment by nik2203** [comment]
#48 Adding Documentation
PES2UG21CS334
Nikhil Girish

**Comment by alfadelta10010** [comment]
!bounty 60

**Comment by alfadelta10010** [comment]
!bounty 120

**Comment by NavinShrinivas** [comment]
!bounty 85

**Pull request merged**
