### PR TITLE
#issue 24 15 4

### PR DESCRIPTION
**Pull request by Vaarun-C**
Fixed several issues in this pull request, I apologize for that. Moved uptime and restart to slash commands. Fixed file not being uploaded issue, Added the scraper cog.

### CODE REVIEW

**Comment by Vaarun-C** [comment]
#24
#15 
#4

**Comment by alfadelta10010** [comment]
!bounty 120

**Comment by alfadelta10010** [comment]
(60+25+25+10 Enthu)

**Comment by alfadelta10010** [comment]
!bounty 110

**Comment by alfadelta10010** [comment]
Removed enthu

**Comment by NavinShrinivas** [comment]
!bounty 100

**Pull request merged**
