### PR TITLE
#issue 21

### PR DESCRIPTION
**Pull request by Vaarun-C**
Worked on issue 21 for the help command to make it more readable, and format it to the required form. Replaced verbose explanations with simpler sentences

### CODE REVIEW

**Comment by alfadelta10010** [comment]
#21

**Comment by alfadelta10010** [comment]
@MaNameEJeff can you get me a screenshot or ping me with the correct output of this code

**Comment by Vaarun-C** [comment]
> @MaNameEJeff can you get me a screenshot or ping me with the correct output of this code

image
image

**Comment by alfadelta10010** [comment]
Ok cool

**Comment by alfadelta10010** [comment]
!bounty 45

**Comment by alfadelta10010** [comment]
!bounty 40

**Comment by NavinShrinivas** [comment]
!bounty 35

**Pull request merged**
