### PR TITLE
Update verification to accept new data style

### PR DESCRIPTION
**Pull request by Keshav1105**
#28 
Keshav Agrawal
PES2UG21CS229
Update verification to accept new data style
I changed all dat values to propervalues

### CODE REVIEW

**Comment by alfadelta10010** [comment]
Approved

**Comment by alfadelta10010** [comment]
!bounty 35

**Comment by alfadelta10010** [comment]
!bounty 10

**Comment by alfadelta10010** [comment]
!bounty 45

**Comment by NavinShrinivas** [comment]
!bounty 35

**Pull request merged**
